### ISSUE TITLE
cmd: xargs

### ISSUE THREAD

**Issue by bpowers** [plasma-umass/browsix#12]
[`xargs(1)`](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/xargs.1?query=kill&sec=1) takes input from stdin and passes it as the `argv` vector to another command.

This should be pretty straightforward, without the need for new syscalls.

**Comment by flat1101** [comment]
Hi, I would like to try implementing this command.

**Comment by bpowers** [comment]
(merged and implemented long ago)
