### ISSUE TITLE
cmd: cp

### ISSUE THREAD

**Issue by bpowers** [plasma-umass/browsix#13]
Don't know how this one slipped by, but of course we should have [`cp(1)`](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/cp.1?query=cp&sec=1).

Most important flag: `-R` (recursive).

**Comment by bpowers** [comment]
fireion from IRC is interested in this

**Comment by hrishikeshgoyal** [comment]
sir I am interested and a bit experienced in implementation of file commands for a unix system. please instruct me further.

**Comment by bpowers** [comment]
@hrishikeshgoyal awesome!  Are you interested in this as part of GSoC, or just in general?  Either way take a look at the [instructions for the starter task](https://github.com/plasma-umass/browsix/wiki/Google-Summer-of-Code-2016-Starter-Task), and the sample workflow at the bottom in particular.

**Comment by hrishikeshgoyal** [comment]
I am interested in this as a part of GSoC. I have Implemented the unix file system driver for Linux kernel in C. Should I start learning Transcripts first?
