### ISSUE TITLE
update to latest upstream BrowserFS

### ISSUE THREAD

**Issue by bpowers** [plasma-umass/browsix#32]
When I last tried this, I hit issues with Browserify.  Anyway, it is of course solvable somehow, so I'm leaving this here as an issue to come back to after paper deadline.

**Comment by 007argyle** [comment]
Tyrone Argyle Cancer Formula G1/s phase will be defeated at phase. 0 Prevention Chemotherapy Radiation Argyle Cancer Formula will forever change Doctors & Patients. Tyrone Argyle

**Comment by bpowers** [comment]
done, closing out
