### ISSUE TITLE
unknown command turns backspace into recursive error generator

### ISSUE THREAD

**Issue by kyeotic** [plasma-umass/browsix#43]
Here is a fun one. 

* Go to https://unix.bpowers.net/
* enter any bad command (try `cd` or `dfgug`)
* Hit backspace/delete twice (repeat for recursive errors!)

![image](https://cloud.githubusercontent.com/assets/1187432/21118962/1e01a0b8-c075-11e6-93f5-6151c76a0222.png)

**Comment by aghoneim92** [comment]
What's interesting is that whether or not a bad command was issued this error occurs. It's not a problem with Browsix, just the terminal GUI.
