### ISSUE TITLE
Build files not in npm package

### ISSUE THREAD

**Issue by golmansax** [plasma-umass/browsix#47]
I'm not sure if this was intended, but the build files in `lib/` are not in the published npm package.  There is a `prepublish` script, and I believe npm is ignoring the generated `lib/` files on publish, because it by default ignores all files in `.gitignore`.

My use case is I'm trying to use `browsix` in a web app and installed `browsix` as an npm dependency.  Thanks!

**Comment by MGageMorgan** [comment]
Good question, I asked two similar questions and have yet to hear back from @bpowers or any of the alumni

**Comment by bpowers** [comment]
Hi @golmansax and @MGageMorgan!  I've just published a new version on npm, v0.9.2, that should have `lib/` included in the package.  Hopefully this fixes your problem, but let me know if it doesn't.

**Comment by golmansax** [comment]
@bpowers I'm running into an error by using the newer version, but I'll file a separate issue with that.  Thanks for the quick response!
