### ISSUE TITLE
broken demo link

### ISSUE THREAD

**Issue by takapiro99** [plasma-umass/browsix#82]
https://github.com/plasma-umass/browsix/blob/master/README.md?plain=1#L54

linked to https://unix.bpowers.net/ is broken...

**Comment by balisujohn** [comment]
That link (https://unix.bpowers.net/) seems to work for me in Firefox.

**Comment by takapiro99** [comment]
thanks @balisujohn

I just checked and I can see it now.
It may have been a temporary problem.
