### ISSUE TITLE
[Question] Completeness of Browsix

### ISSUE THREAD

**Issue by james-pre** [plasma-umass/browsix#89]
How complete is Browsix? By complete, I mean a complete POSIX kernel.

Browsix is the coolest project I've seen in my 5 years of programming. I was trying to make an in-browser operating system from scratch a few months ago but failed due to the complexity (which I was not ready for).

I would love to work on Browsix, and I would like to know how capable it is right now and how complete it is.

**Comment by emeryberger** [comment]
Probably it'd be good to take a look at the technical paper to see what is implemented. We've used it to run numerous applications (including LaTeX). See:
* https://arxiv.org/abs/1611.07862
* https://arxiv.org/abs/1901.09056
